<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE persona [
<!ELEMENT persona (nombre,nacimiento,direccion,varon)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nacimiento EMPTY>
<!ATTLIST nacimiento dia CDATA #REQUIRED>
<!ATTLIST nacimiento mes CDATA #REQUIRED>
<!ATTLIST nacimiento anyo CDATA #REQUIRED>
<!ELEMENT direccion (calle,poblacion,provincia,cpostal)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cpostal (#PCDATA)>
<!ELEMENT varon EMPTY>
] >

<persona>

  <nombre>Juan Pardo</nombre>

  <nacimiento dia="10" mes="Abril" anyo="1982" />

  <direccion>
    <calle>"caoba 1"</calle>
    <poblacion>Madrid</poblacion>
    <provincia>Madrid</provincia>
    <cpostal>28005</cpostal>
  </direccion>

  <varon />
</persona>
