=== Steve6731/ASIR-1/LM/1ºEVA/examen1eva/musica.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="musica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="musico" type="tipoMusico" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    
    <xs:complexType name="tipoMusico">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="apellidos" type="xs:string"/>
            <xs:element name="nacido" type="tipoTimepo"/>
            <xs:element name="fallecido" type="tipoTimepo" minOccurs="0"/>
            <xs:element name="origen" type="tipoOrigen"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoTimepo">
        <xs:sequence>
            <xs:element name="dia" type="xs:integer"/>
            <xs:element name="mes" type="xs:integer"/>
            <xs:element name="anio" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoOrigen">
        <xs:attribute name="pais" type="xs:string"/>
    </xs:complexType>

</xs:schema>

=== Steve6731/ASIR-1/LM/1ºEVA/examen1eva/musica.xml
<?xml version="1.0" encoding="UTF-8"?>
<musica xsi:noNamespaceSchemaLocation="musica.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <musico>
    <nombre>Antonio</nombre>
	<apellidos>Vivaldi</apellidos>
    <nacido>
      <dia>4</dia>
      <mes>3</mes>
      <anio>1678</anio>
	</nacido>
    <fallecido>
      <dia>28</dia>
      <mes>7</mes>
      <anio>1741</anio>
	</fallecido>
	<origen pais="Italia"/>
  </musico>  
  <musico>
    <nombre>Johannes</nombre>
    <apellidos>Mozart</apellidos>
    <nacido>
      <dia>27</dia>
      <mes>1</mes>
      <anio>1756</anio>
	</nacido>
    <fallecido>
      <dia>5</dia>
      <mes>12</mes>
      <anio>1791</anio>
	</fallecido>
	<origen pais="Austria"/>
  </musico>
  <musico>
    <nombre>Ludwig Van</nombre>
    <apellidos>Beethoven</apellidos>
    <nacido>
      <dia>16</dia>
      <mes>12</mes>
      <anio>1770</anio>
	  </nacido> 
	  <origen pais="Alemania"/>
  </musico>
  
</musica>
