=== Steve6731/ASIR-1/LM/1ºEVA/Schema/XSD_D1a.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Ejercicios">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ejercicio1" type="Eje1"/>
                <xs:element name="ejercicio2" type="Eje2"/>
                <xs:element name="ejercicio3" type="Eje3"/>
                <xs:element name="ejercicio4" type="Eje4"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Eje1">
        <xs:sequence>
            <xs:element name="cantidad" type="typeCantidad"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="typeCantidad">
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="+30"/>
            <xs:minInclusive value="-30"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Eje2">
        <xs:sequence>
            <xs:element name="cantidad" type="typeCantidad2" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="typeCantidad2">
        <xs:simpleContent>
            <xs:extension base="xs:float">
                <xs:attribute name="divisa" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="Eje3">
        <xs:sequence>
            <xs:element name="cantidad" type="typeCantidad3" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="typeCantidad3">
        <xs:simpleContent>
            <xs:extension base="FormCantidad">
                <xs:attribute name="divisa" type="FormDivisa"></xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="FormCantidad">
        <xs:restriction base="xs:float"/>
    </xs:simpleType>

    <xs:simpleType name="FormDivisa">
        <xs:restriction base="xs:string">
            <xs:enumeration value="euro"/>
            <xs:enumeration value="dolar"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Eje4">
        <xs:sequence>
            <xs:element name="codigo" type="typeCodigo"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="typeCodigo">
        <xs:simpleContent>
            <xs:extension base="FormCode">
                <xs:attribute name="sede" type="FormSede"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="FormCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2}[0-9]{2}[A-Za-z]{3}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="FormSede">
        <xs:restriction base="xs:string">
            <xs:enumeration value="EspaÃ±a"/>
            <xs:enumeration value="China"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Steve6731/ASIR-1/LM/1ºEVA/Schema/XSD_D1.xml
<?xml version="1.0" encoding="UTF-8"?>

<Ejercicios
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="XSD_D1a.xsd"
>
    <ejercicio1>
        <cantidad>20</cantidad>
    </ejercicio1>

    <ejercicio2>
        <cantidad divisa="euro">20</cantidad>
        <cantidad divisa="dolar">18.32</cantidad>
    </ejercicio2>

    <ejercicio3>
        <cantidad divisa="euro">20</cantidad>
        <cantidad divisa="dolar">18.32</cantidad>
    </ejercicio3>

    <ejercicio4>
        <codigo sede="EspaÃ±a">AA23Abc</codigo>
    </ejercicio4>

</Ejercicios>
